{{- if .Values.service.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "s3manager.fullname" . }}
  labels:
    {{- include "s3manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.ports}}
    - port: {{ .servicePort }}
      targetPort: {{ .targetPort }}
      nodePort: {{ .nodePort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
    {{- range .Values.service.additionalPorts }}
    - port: {{ .servicePort }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "s3manager.selectorLabels" . | nindent 4 }}
{{- end }}